print('==========FORM PENGISIAN SALDO DANA========')
nomer=int(input("nomer anda:"))
nominal=int(input("masukan nominal anda:"))
uang=int(input ("masukan uang anda:"))
total=(uang-nominal)
print(nomer,nominal,uang,total)
print("SELAMAT ANDA BERHASIL TOP UP SALDO DANA")
print('NOMER DANA       :',nomer)
print('NOMINAL          :',nominal)
print("UANG ANDA        :",uang)
print("KEMBALIAN ANDA   : ",total)
print("========SELAMAT MENIKMATI SALDO DANA ANDA========")